name: Diego del Alamo, PhD
description: Personal website
meta_description: "Diego del Alamo's personal website"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "http://delalamo.github.io"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Diego del Alamo"

# Disqus config
disqus-shortname: ""
